### ISSUE TITLE
Sales Return doesnot allow return of valid items 

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#119]
The detail of direct sale items is as below
![sales](https://cloud.githubusercontent.com/assets/6284880/6616070/40c8b3ee-c8d2-11e4-82f1-0a09c2a99605.PNG)

when I try to return a dozen based on the above invoice i get an error message as below
![return](https://cloud.githubusercontent.com/assets/6284880/6616082/6477cc08-c8d2-11e4-815e-ba70d97cdf55.PNG)

**Comment by mixerp** [comment]
Could you please verify that the following commit properly solves this issues:

[https://github.com/mixerp/mixerp/commit/71ae09d9d27df0e1ebadcdfecc31b22550c86fa5](https://github.com/mixerp/mixerp/commit/71ae09d9d27df0e1ebadcdfecc31b22550c86fa5)

Please feel free to close the issue if you think the above commit solves the problem.
