### ISSUE TITLE
Purchase Return Issue

### ISSUE THREAD

**Issue by mixerp3** [mixerp/mixerp#121]
Screenshot of account statement.
![account](https://cloud.githubusercontent.com/assets/10184034/6638548/56884248-c9af-11e4-9a20-f7825ad6e257.PNG)

Screenshot of Trial Balance.
![trial](https://cloud.githubusercontent.com/assets/10184034/6638556/64980f62-c9af-11e4-818f-d3f0ee177a4f.PNG)

Difference in purchase discount amount in trial balance and account statement.

**Comment by mixerp** [comment]
How can we reproduce his issue? Could you please post step by step process in order to reproduce this?

**Comment by gguruss** [comment]
first we started with the purchase of items including discount
![step1](https://cloud.githubusercontent.com/assets/6284880/6645662/85abde86-c9e6-11e4-8887-b3a7da92e956.PNG)
after the items has been purchased we return it
![step2](https://cloud.githubusercontent.com/assets/6284880/6645675/a21e8f46-c9e6-11e4-97c1-6dc2a392dbf9.png)
the purchased item has been returned but without discount
![step3](https://cloud.githubusercontent.com/assets/6284880/6645689/c1ee3e52-c9e6-11e4-9534-00c243f9a92c.PNG)
now we verify the purchase return
![step4](https://cloud.githubusercontent.com/assets/6284880/6645714/e8967088-c9e6-11e4-87fb-1127ff56066d.PNG)
after verification the report for purchase discount ledger is as follows
![step5](https://cloud.githubusercontent.com/assets/6284880/6645727/0e447668-c9e7-11e4-9afe-f2af3837c274.PNG)
however in trial balance the amount in purchase discount ledger is different
![step6](https://cloud.githubusercontent.com/assets/6284880/6645752/32e08bf6-c9e7-11e4-86d3-8968a262bea5.PNG)

**Comment by mixerp** [comment]
Hi, I was unable to reproduce the issue. Could you please take the latest changeset and start from scratch to test if this issue can be reproduced?

**Comment by mixerp3** [comment]
While creating "Direct Purchase" with the discount amount, the account "Purchase Discount" in Trial Balance does not update with the discount amount.

**Comment by mixerp** [comment]
Cannot reproduce this issue. Please feel free to reopen if you can reproduce this.
