### ISSUE TITLE
Stock Transfer Journal saving to different book name and generating view from different book

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#140]
Stock transfer journal is saving data to Stock.Transfer book name whereas the view is asking data from Inventory.Transfer.

The db function transactions.post_stock_journal saves the data to Stock.Transfer whereas the stock transaction view asks data as
  view.Book = TranBook.Inventory;
   view.SubBook = SubTranBook.Transfer;

**Comment by mixerp** [comment]
The correct term should be "Inventory.Transfer".
