### ISSUE TITLE
Can not change (Reset) password for user from office setup/user management

### ISSUE THREAD

**Issue by nubiancc** [mixerp/mixerp#197]

**Comment by gguruss** [comment]
To change password please go to **Back Office/Admin Tools/Change User Password** . Make sure that the user has **Can change password**  set to **Yes** in **Office Setup/ User Management**.

**Comment by nubiancc** [comment]
mean when the user forgets the password or htere are problem in user login , the system administrator can change the password or reset it??

**Comment by mixerp** [comment]
System administrator can change user password by visiting the page:

Back Office --> Admin Tools --> Change User Password.

This feature is currently disabled on hosts other than "localhost". We are working on it and a fix will be ready before the Beta 1 Version 2 release. :)
