### ISSUE TITLE
User management work localy 

### ISSUE THREAD

**Issue by nubiancc** [mixerp/mixerp#199]
when access User management from local server it work but when access from remotly show "You are not authorized to access this resource at this time."

**Comment by mixerp** [comment]
Hi nubiancc, we have solved this issue for your convenience. The configuration file "MixERP.xml" now has a setting called "Mode":

https://github.com/mixerp/mixerp/blob/master/src/FrontEnd/MixERP.Net.FrontEnd/Resource/Configuration/MixERP.xml#L28

Please change the values of the setting "Mode" from "Development" to "Production" when you are hosting MixERP in a live environment.

**Comment by mixerp** [comment]
Please feel free to reopen this issue if you think that you issue was not completely solved.
