### ISSUE TITLE
Receipt from customer can't be saved.

### ISSUE THREAD

**Issue by mixerp3** [mixerp/mixerp#205]
When we click on save button it shows the error:

ERROR: 42883: function transactions.post_receipt(character varying, integer, integer, bigint, date, integer, character varying, text, boolean, integer, character varying, integer, integer, integer, character varying, integer, boolean, transactions.stock_detail_type[], core.attachment_type[], bigint[]) does not exist.

**Comment by mixerp** [comment]
Please feel free to reopen this if you have steps to reproduce this issue.
