### ISSUE TITLE
Cash in hand account doesn't merge with same currency.

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#207]
![journal voucher](https://cloud.githubusercontent.com/assets/10184034/7313156/817c9778-ea76-11e4-988e-a7c1da99ff1a.png)

In journal voucher entry, cash in hand with different amount but with the same currency and repository
says duplicate entry.

**Comment by gguruss** [comment]
I think we are not allowed to add duplicate accounts. According to the code the account can only be used once.

**Comment by mixerp3** [comment]
If someone enters his whole day vouchers at the end, it will be problem for them..

**Comment by mixerp3** [comment]
Invalid.
