### ISSUE TITLE
Saving problem in bank transaction in receipt from customers.

### ISSUE THREAD

**Issue by mixerp3** [mixerp/mixerp#208]
Entering the receipt transaction, select the cash button and then cash repository, and then  realized that this transaction is a bank transaction.So, clicked on bank button and entered the remaining values
which leads to:

A cash transaction cannot contain bank transaction details.

![receipt](https://cloud.githubusercontent.com/assets/10184034/7313578/13776da2-ea7b-11e4-9199-d92d00ccde04.png)

**Comment by mixerp** [comment]
You cannot specify both "Cash Repository" and "Bank A/C" on a receipt transaction. Go to cash tab and remove the selection of cash repository if you want this as receipt on Bank A/C.
