### ISSUE TITLE
Compound Unit of Measure with same base unit name takes the latter value

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#218]
![cuom](https://cloud.githubusercontent.com/assets/6284880/7517333/25698454-f4f4-11e4-9936-5c690603e3dc.PNG)

before entry conversion value
![before](https://cloud.githubusercontent.com/assets/6284880/7517476/fee1d22c-f4f4-11e4-8695-9829062e28a7.png)

after entry conversion value
![after](https://cloud.githubusercontent.com/assets/6284880/7517487/0b0836d6-f4f5-11e4-9d6f-fe68345a8b21.png)

**Comment by mixerp** [comment]
Please feel free to close the issue if the commit:

https://github.com/mixerp/mixerp/commit/7b111e591db383ba5b1bdfae47b27f744f6dfd53

fixed this issue. :+1:
