### ISSUE TITLE
bug in report engine

### ISSUE THREAD

**Issue by grgkrishna** [mixerp/mixerp#22]
Case:
1.two funcions in the postgresql database are overloaded with same number of parameters but different datatype like
    get_product_details(product_id integer) and 
    get_product_details(product_name character varying)
2.All command parameters are passed as strings in the report engine
problem: 
1.since the command parameters are passes as strings ,the first function with integer parameter wont get executed at all
2 if the second function was not there then the first function get executed even if we are passing the string parameter

**Comment by mixerp** [comment]
Fixed.
