### ISSUE TITLE
Direct sales item discount error

### ISSUE THREAD

**Issue by nubiancc** [mixerp/mixerp#221]
when set discount to soled item and save get error

![mix](https://cloud.githubusercontent.com/assets/10084587/7534953/853ed980-f588-11e4-981d-9026b6602481.png)

**Comment by gguruss** [comment]
Hey nubiancc, 
I am sorry I could not reproduce your problem. Could you please post your problem in detail to our forum http://mixerp.org/erp/kunena/index.html.
