### ISSUE TITLE
getting errors in journal voucher entry

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#23]
![image](https://cloud.githubusercontent.com/assets/6284880/4197396/0e3b42fe-37e9-11e4-8ea7-2ef48a258122.png)

Getting some error when pressing undo for the uploaded documents.Maybe a descriptive error would be of help.

also when posting the transaction i get the following error
![image](https://cloud.githubusercontent.com/assets/6284880/4197412/6a00cff0-37e9-11e4-9ca3-0d14aacd1dac.png)

**Comment by mixerp** [comment]
Fixed.
