### ISSUE TITLE
Grid of StockTransactionFactory allows deletion of row while updating which leads to empty grid

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#232]
![image](https://cloud.githubusercontent.com/assets/6284880/7680227/36a613a2-fd84-11e4-97bb-7a382391c110.png)

**Comment by mixerp** [comment]
Does the commit #6dc3d3118c07913bf31c8cb80c76add0f1c25299 fix this issue? If it does, please feel free to close this. :)
