### ISSUE TITLE
Scrud needs to handle unique constraints

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#24]
I try adding a duplicate account name like 'Investment' which already exists.

![image](https://cloud.githubusercontent.com/assets/6284880/4199718/63724898-3808-11e4-822f-c77c7bbcd92d.png)

and i get an error like this

![image](https://cloud.githubusercontent.com/assets/6284880/4199742/8b1ba2d6-3808-11e4-931c-1874b8a0ca00.png)

maybe it needs a mechanism to show user that the account name already exists and to choose a different account name

**Comment by mixerp** [comment]
Fixed.
