### ISSUE TITLE
Database error on install

### ISSUE THREAD

**Issue by Skrypt** [mixerp/mixerp#257]
I'm trying to run the latest code from github by cloning the repository. I can't make it work. The database script is making an error on the datetimes format when trying to execute the sql file(s).

**Comment by Skrypt** [comment]
Changed DateStyle configuration in postgresql.conf that did the trick
datestyle = 'iso, mdy'
Maybe adding this to the installation documentation.

**Comment by mixerp** [comment]
Thanks for pointing out. I have added a label for that. :+1:

**Comment by mixerp** [comment]
Fixed in the latest database bundle.
