### ISSUE TITLE
unique constraint error handled first time when clicking save,but on saving with the same values gives an error

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#26]
I enter the following values, the MoF already exists in db but still i try to input it
![image](https://cloud.githubusercontent.com/assets/6284880/4677078/d89d382e-55e2-11e4-933e-015a6522026a.png)
on first save it highlights the error but if i press save again the following gets generated
![image](https://cloud.githubusercontent.com/assets/6284880/4677055/9d4536e6-55e2-11e4-99f4-006123e53327.png)

**Comment by mixerp** [comment]
Fixed.
