### ISSUE TITLE
Resource ScrudResource.maintained_by was not found (Bank Account).

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#266]
While creating bank account the above mentioned error occurs and bank account could not be created.

**Comment by mixerp3** [comment]
Bank account cannot be created.
![bank](https://cloud.githubusercontent.com/assets/10184034/8282896/7327cb9a-1913-11e5-8775-ac79751bb7a7.png)

**Comment by mixerp** [comment]
Thank you for reporting the issue. +1

**Comment by mixerp3** [comment]
Solved.
