### ISSUE TITLE
Stock cannot be transferred eventhough stock is sufficient (Stock Transfer Journal).

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#278]
While selecting language (Deutsch-Österreich), in the Stock Transfer Journal, there shows an error message of insufficiency although the stock is available.
![stock transfer](https://cloud.githubusercontent.com/assets/10184034/8283025/46380f18-1914-11e5-803d-dfcc605a4e43.png)

**Comment by mixerp** [comment]
Thank you for the bug submission.
