### ISSUE TITLE
Currency (Hundredth) separator missing (Deutsch-Österreich) .

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#279]
Hundredth separator (.) is missing in every grid view and reports.
![list](https://cloud.githubusercontent.com/assets/10184034/8283567/ba6037f0-1917-11e5-93cb-72ef7118fab6.png)
![report](https://cloud.githubusercontent.com/assets/10184034/8283639/22b8bf7a-1918-11e5-96be-2a0247bcd7ec.png)

**Comment by mixerp** [comment]
Thank you for submitting the bug.

**Comment by mixerp** [comment]
What is the status of this issue?

**Comment by mixerp3** [comment]
This issue is valid. There is no hundredth separator in any of the cultures.

**Comment by mixerp** [comment]
Do you mean thousand separator?

**Comment by mixerp3** [comment]
Yes. thousand separator.
