### ISSUE TITLE
Could not save transaction on Direct Sales (Deutsch-Österreich).

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#280]
ERROR: 23514: value for domain money_strict violates check constraint "money_strict_check".
Same problem in:
a) Sales Quotation
b) Sales Order
c) Direct Purchase
d) Purchase Order
e) GRN Entry
![sales](https://cloud.githubusercontent.com/assets/10184034/8286697/c8071c30-192a-11e5-9d78-0f24125948e6.png)

**Comment by mixerp** [comment]
What is the status of this issue?

**Comment by mixerp3** [comment]
Working fine.
