### ISSUE TITLE
Journal Voucher cannot be posted (Deutsch-Österreich).

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#282]
While posting journal in (Deutsch-Österreich) language, error "Invalid Data" occurs.
![journal](https://cloud.githubusercontent.com/assets/10184034/8288463/0bd9d956-1936-11e5-8f4c-134047c2844f.png)

**Comment by mixerp** [comment]
What is the status of this issue?

**Comment by mixerp3** [comment]
No problem with this issue now.
