### ISSUE TITLE
Could not save opening balance on opening Inventory (Deutsch-Österreich).

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#284]
ERROR: 23514: value for domain money_strict violates check constraint "money_strict_check".
![opening](https://cloud.githubusercontent.com/assets/10184034/8289194/93940ef8-193a-11e5-9a23-4b08c7d0bbc2.png)

**Comment by mixerp** [comment]
What is the status of this issue?

**Comment by mixerp3** [comment]
No problem.
