### ISSUE TITLE
Party with same name can't be created.

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#302]
While creating party, party with same name cannot be created.
And party with different name but same first 2 alphabets of first name and 3 alphabets of last name
also cannot be created. eg. Jason Smith cannot be created.
![party](https://cloud.githubusercontent.com/assets/10184034/8406791/c31f9a58-1e7f-11e5-832a-6ceca5f1f66f.png)

**Comment by mixerp3** [comment]
Solved.
