### ISSUE TITLE
LC Debit  shows wrong total in journal voucher entry.

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#303]
When we update exchange rate from open exchange rate, the total lc debit is incorrect while entering voucher in journal voucher entry.

**Comment by nubiancc** [comment]
LC Credit mean letter of Credit ?

**Comment by gguruss** [comment]
LC refers to Local currency nubiancc.You should join us on our forum.We have more information and discussions there.
http://mixerp.org/erp/forum/index.html

**Comment by mixerp** [comment]
What is the status of this issue?

**Comment by mixerp3** [comment]
This is working fine now.
