### ISSUE TITLE
Error when trying to open 'top sold Items in Sales menu 'password authentication failed'

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#310]
HI! When trying to open that view I crashed and got that error  28P01
![error when trying to open top sales](https://cloud.githubusercontent.com/assets/12976491/8466419/da513838-2052-11e5-936b-8fcd8cdf87be.JPG)

**Comment by gguruss** [comment]
Johann please open the file ReportParameters.config inside the following path
src\FrontEnd\MixERP.Net.FrontEnd\Resource\Configs

in that file there is a line
    <add key="DbServerDatabase" value="mixerp" />

put the name of your database in the value. I think after that it should work.

**Comment by Johann-Schwarz** [comment]
There are lots of config files which one are you talking about

**Comment by gguruss** [comment]
The file name is ReportParameters.config
 also put your password in this line that binod gave you

add key="DbServerPassword" value="change-on-deployment"

**Comment by Johann-Schwarz** [comment]
Done! Sorry totally overlooked that you had written this in your post on the Top already. Works!

**Comment by mixerp** [comment]
IMO, we should get rid of the appSetting "DbServerPassword" in favor of DBServer.config's settings. I am referencing this issue as a bug.

**Comment by Johann-Schwarz** [comment]
Yea  I also cannot understand having a password here again, because IMHO we would get in troubles when changing between different databases would need to change the value here
add key="DbServerDatabase" value="mixerp"  // mixerp2, company,whatever

**Comment by ZQShiekh** [comment]
Hi ,
I am zeeshan need help in MixERP ERROR: 42P01: relation "config.mixerp" does not exist this erro I am trying every thing but cant resolve please help urgently thanks
