### ISSUE TITLE
Report Command Panel Icons without ToolTip Text

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#311]
![no tooltip texts](https://cloud.githubusercontent.com/assets/12976491/8473951/680f0da8-20ad-11e5-9c05-4853e557ed52.JPG) There are no tool Tipps in different places like the signs at the end of a grid,
and also here in the reports

**Comment by gguruss** [comment]
lol we totally overlooked this one. I wil add a label to it.
