### ISSUE TITLE
Calculation Error in Tax  still there

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#312]
HI !
This error has changed Total amount now works fine ,
My price is set as price including tax in the example it is 180 and the tax is 20 % set to'20' in the Tax file
 calculating the itemprice  excluding tax gives 150 so this is fine.
Adding up the items also works finr now
But calculating the tax amount is an error here as it's value  should be 30 but is 0,3
so there is still an error here
![tax calculation error price incl tax](https://cloud.githubusercontent.com/assets/12976491/8477591/810a91ba-20cb-11e5-8fdc-d7633f7ded4e.JPG)

**Comment by mixerp** [comment]
Hi,

I could not reproduce this issue. Could you please email your current database to support@mixerp.org?

**Comment by Johann-Schwarz** [comment]
I would do that but can you tell me how to do that I don’t know how to copy or creating a backup file in postgres SQL

THx Jonny

 

Von: MixERP [mailto:notifications@github.com] 
Gesendet: Donnerstag, 02. Juli 2015 20:28
An: mixerp/mixerp
Cc: Johann Schwarz
Betreff: Re: [mixerp] Calculation Error in Tax still there (#312)

 

Hi,

I could not reproduce this issue. Could you please email your current database to support@mixerp.org?

**Comment by mixerp** [comment]
You can use backup feature provided by MixERP or by following this link.

http://www.pgadmin.org/docs/dev/backup.html

**Comment by Johann-Schwarz** [comment]
Here is the backup. I hope I did it correctly

 

Von: MixERP [mailto:notifications@github.com] 
Gesendet: Freitag, 03. Juli 2015 17:16
An: mixerp/mixerp
Cc: Johann Schwarz
Betreff: Re: [mixerp] Calculation Error in Tax still there (#312)

 

You can use backup feature provided by MixERP or by following this link.

http://www.pgadmin.org/docs/dev/backup.html

**Comment by mixerp** [comment]
We received your backup. Thank you.
