### ISSUE TITLE
Direct Sale and Quotation  date not actual 

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#314]
When opening a new direct sale or quotation iMHO  the date in the dateTime field should be the actual date not any date weeks ago.  See attached.
![date in directsales and qotation not actual](https://cloud.githubusercontent.com/assets/12976491/8503226/4ecb6066-21bc-11e5-8b6f-5871ef5e27c1.JPG)

**Comment by Johann-Schwarz** [comment]
sorry pressed wrong button

**Comment by mixerp** [comment]
No, we do not use system clock or computer date at all. Please refer to the following documentation:

http://docs.mixerp.org/docs/user-guide/core-concepts/current-date.html

**Comment by Johann-Schwarz** [comment]
ok so this is obviously no error because the last EOD operation I did in my testing db was in this time..
