### ISSUE TITLE
Error message in store dropdown list. 

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#317]
![store](https://cloud.githubusercontent.com/assets/10184034/8507909/f9648bcc-2277-11e5-9254-154fde6f5cd9.png)

**Comment by mixerp** [comment]
Could you please make sure that you have updated your database along with the code?

**Comment by Johann-Schwarz** [comment]
sorry this was no problem of me . I don't have a Party called Jasmi-0002 , Must have been sent from another user

**Comment by mixerp3** [comment]
Invalid.
