### ISSUE TITLE
Wrong naming in Quotation printout

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#326]
![quotation naming error](https://cloud.githubusercontent.com/assets/12976491/8541361/d4a99986-248d-11e5-80ed-4072ab3f3daa.JPG)
The naming in the quotation itself is wrong because the details are no 'Invoice Details ' because we have no order so we have no 'invoice'. To avoid confusion for the mixERP-users customers  it has to be 'quotation details'. Otherwise we are creating confusion.

**Comment by mixerp** [comment]
Fixed
