### ISSUE TITLE
URGENT Demo on Web crashes when trying to load it

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#333]
![website error crashes when starting](https://cloud.githubusercontent.com/assets/12976491/8566228/0eef3a54-255d-11e5-8d3f-617ec18edfb0.JPG)

I tried to open the website demo database but it crashes see attached errormessage

**Comment by gguruss** [comment]
fixed.

**Comment by Johann-Schwarz** [comment]
yea this works fine now
