### ISSUE TITLE
Bug just after trying to Login

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#334]
![errorjust afterlogin](https://cloud.githubusercontent.com/assets/12976491/8633146/6dc0d6b8-27bb-11e5-91be-b1e4f9101359.JPG)

The Error message now is no more that an ID is missing its now changed but still cannot use any menue, even break just after login. Independent If I want to login in German or English.

**Comment by mixerp** [comment]
Please rebuild the solution and your issue will be gone.

**Comment by Johann-Schwarz** [comment]
Jep this is handled when I rebuilt the solution but then I again got the ID Eror ( BTW Database is updated and my branch is even
![id error](https://cloud.githubusercontent.com/assets/12976491/8633598/77364146-27d0-11e5-9938-f20204aec1b0.JPG)

**Comment by gguruss** [comment]
I think you need to run rebundle and re-run with sample in the path

src\FrontEnd\MixERP.Net.FrontEnd\db\release-1\update-1

after that run the incremental sample script in pgAdmin. I am pretty sure after that it would work.

**Comment by Johann-Schwarz** [comment]
Hi !



I’m afraid I have created some mixup now.

Aster I did the described action I got a document on screen where I should add Username, officeame Currency and all that. Looks like it would create a new database.

I entered the data and now I cannot open the sample database nor I can open the company database

Whatever I enter into login it says invalid login.

So IMHO I should delete the databases on postgres and create a totally new one, beginning with a fesh and empty database. IMHO this is also the best because then all the incorrect records that contains wrong tax calculation would be gone and I can create a new database. 

Maybe the errors then would be gone because the rebundle was done with success

 

Von: gguruss [mailto:notifications@github.com] 
Gesendet: Samstag, 11. Juli 2015 15:52
An: mixerp/mixerp
Cc: Johann Schwarz
Betreff: Re: [mixerp] Bug just after trying to Login (#334)

 

I think you need to run rebundle and re-run with sample in the path

src\FrontEnd\MixERP.Net.FrontEnd\db\release-1\update-1

after that run the incremental sample script in pgAdmin. I am pretty sure after that it would work.

**Comment by Johann-Schwarz** [comment]
I did rebundle and recompiled the program, also repaired my database and now it works fine
