### ISSUE TITLE
Login View Issue

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#335]
When starting program the Login Screen shows up and mixerp is the selected database, but the selected branch shows up the branches of my 'company' database. When I select the database by changing it to 'company' and back to mixerp then the branches are shown correctly. So you have an error by loading the related  data when starting the Login View.
![login view bug](https://cloud.githubusercontent.com/assets/12976491/8633236/aa93789a-27be-11e5-9a77-117f23abafc8.JPG)

**Comment by mixerp** [comment]
Please change the order of "Catalogs" in DBServer.config so that the default database appears first.
