### ISSUE TITLE
NamespaceErrors and not existing Namespaces

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#366]
![programming errors](https://cloud.githubusercontent.com/assets/12976491/8781309/861efe24-2f0e-11e5-9edc-67ffe9155e48.JPG)
IÄm relatively sure that the namespace should be MixERP.Net and not MixER,Net, but there are additional Namespaces missing and this creates 28 errors
I hd downloaded the most actual data of the micerp matser

**Comment by gguruss** [comment]
Sorry this was a mistake push from my side.I was testing pull request from branch. I accidentally made a push

**Comment by mixerp** [comment]
Solved. Please revert to the commit cdaa2cf6faa4d787ba09791afca16031b2017ca3.
