### ISSUE TITLE
itemselector search bug

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#37]
while searching the ledger in the itemselector through search box
![image](https://cloud.githubusercontent.com/assets/6284880/5870178/b99a377e-a2ef-11e4-9101-9c06d411ecc5.png)

getting error
![image](https://cloud.githubusercontent.com/assets/6284880/5870185/f0cd5550-a2ef-11e4-972f-acc2e82e2dcd.png)

also why does the account master id dropdown has only few ledgers?

**Comment by binodnp** [comment]
Solved.

**Comment by mixerp7** [comment]
Very  good start on the very first day.
Welcome Guru Singh dai, on our MixERP. :)
