### ISSUE TITLE
ERP System Current Date

### ISSUE THREAD

**Issue by nubiancc** [mixerp/mixerp#377]
I can't know the current date of ERP system, and default date is current computer date and other 1/1/0001

because the system workfolw change date after EOD operation ,i suggest display current system date above on menu

**Comment by Johann-Schwarz** [comment]
I would suggest to set the current date to the installation date as ling as there is no eod operation done

**Comment by gguruss** [comment]
this was caused due to the ending of fiscal year. Since the current fiscal year has ended and there is no data for another fiscal year the date is 1/1/0001. Just create a new fiscal year and the problem should be solved. Meanwhile the next version will address the problem of the fiscal year.

**Comment by mixerp3** [comment]
Solved.
