### ISSUE TITLE
ERROR: 42P01: relation "config.mixerp" does not exist

### ISSUE THREAD

**Issue by ahmedelbaradey** [mixerp/mixerp#383]
Always Show When Start Application
![jpg](https://cloud.githubusercontent.com/assets/12929612/9009303/83a2cf00-37a0-11e5-9fbc-12e486ced0f7.jpg)

**Comment by mixerp** [comment]
Whenever a new source is pulled from github, you need to run the patch file:

`/src/FrontEnd/MixERP.Net.FrontEnd/db/patch.sql`

https://raw.githubusercontent.com/mixerp/mixerp/master/src/FrontEnd/MixERP.Net.FrontEnd/db/patch.sql

**Comment by midrees** [comment]
I am also facing the same error message: ```

An exception of type 'MixERP.Net.Framework.MixERPException' occurred in PetaPoco.dll but was not handled in user code

Additional information: ERROR: 42P01: relation "config.mixerp" does not exist
```
I also tried patch.sql but getting following error when running patch.sql:
`ERROR:  column "book_date" of relation "transaction_master" does not exist`
