### ISSUE TITLE
Ugly Screen when trying to create Parties

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#409]
I opened the parties Screen and it looks like. There are artefacts of a pictureframe on the screen
![partues setup](https://cloud.githubusercontent.com/assets/12976491/9288480/deda200e-4348-11e5-8a7e-693efe564971.JPG)

**Comment by mixerp** [comment]
Sent a teamviewer invitation.

**Comment by Johann-Schwarz** [comment]
you can anyway come to my PC using team so we can check that issues I'll start facebook and waiting for getting  a sign that someone wants to chat
