### ISSUE TITLE
export ofquotation  to excel does not work properly

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#411]
I have done a short estimate to test the new feature and created an excel file out of it
The logo overlaps with the text as you can see in the screen shot
Additional before excel opens the document it gives a message that the data it contains doesn't fit to the excel version indicated by .xls  file ending.
![excel exportfile problem](https://cloud.githubusercontent.com/assets/12976491/9288717/0c4506b4-4356-11e5-9b67-8881c5cdc7a4.JPG)

**Comment by mixerp** [comment]
You need to change the header.html file and added fixed height for your logo image if the logo is too big.

**Comment by mixerp** [comment]
You need to change the header.html file and add a fixed height for your logo image since the logo is too big.
