### ISSUE TITLE
pdf file export summaryzies how often the button is pressed

### ISSUE THREAD

**Issue by Johann-Schwarz** [mixerp/mixerp#412]
If you export a pdf it works properly the first time, If you doo it again for any reason you will have the same document added to the pdf file and it nów contains two files. And so on. I have added apdf which contains the same document 4 times. This should not happen. If the button is pressed a second time you should be asked if you wan to store or overwrite the already existing one, then creating it. ups sorry I cannot upload pdf here
![wrong pdf storing](https://cloud.githubusercontent.com/assets/12976491/9288735/0721fd8a-4357-11e5-9b65-d30fcdad1b02.JPG)

**Comment by mixerp** [comment]
Are you sure that you have refreshed your browser cache?
