### ISSUE TITLE
Some Error When Buld MixERP

### ISSUE THREAD

**Issue by nubiancc** [mixerp/mixerp#416]
I get Some Error When Building  MixERP

![untitled](https://cloud.githubusercontent.com/assets/10084587/9299678/9f87969e-44be-11e5-8f01-ad5cbda7fb56.png)

![untitled1](https://cloud.githubusercontent.com/assets/10084587/9299709/e66823bc-44be-11e5-909c-f58f6dfa6447.png)

**Comment by mixerp3** [comment]
Solved.
