### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by mak1911** [mixerp/mixerp#461]
Error 1 Invalid expression term '.' G:\MixERP_LatestSource_27Nov15\mixerp-master\src\Libraries\Logic\MixERP.Net.EntityParser\PocoHelper.cs 34 22 MixERP.Net.EntityParser
Error 2 Syntax error, ':' expected G:\MixERP_LatestSource_27Nov15\mixerp-master\src\Libraries\Logic\MixERP.Net.EntityParser\PocoHelper.cs 34 23 MixERP.Net.EntityParser
Error 3 Invalid expression term '.' G:\MixERP_LatestSource_27Nov15\mixerp-master\src\Libraries\Logic\MixERP.Net.EntityParser\PocoHelper.cs 70 26 MixERP.Net.EntityParser
Error 4 Syntax error, ':' expected G:\MixERP_LatestSource_27Nov15\mixerp-master\src\Libraries\Logic\MixERP.Net.EntityParser\PocoHelper.cs 70 27 MixERP.Net.EntityParser

**Comment by mixerp** [comment]
Please follow the developer documentation here:

http://docs.mixerp.org/docs/developer/index.html

It seems that you dont have Visual Studio 2015.
