### ISSUE TITLE
Not able to run the website from IIS

### ISSUE THREAD

**Issue by allenpaulp** [mixerp/mixerp#464]
I followed all the steps mentioned in:
http://docs.mixerp.org/docs/deployment/iis.html

is there anything more that I have to do?
Because when i click explore on IIS, it goes to http://intranet.mixerp.net/ and shows that the webpage is not available

**Comment by mixerp** [comment]
Allenpaulp, `intranet.mixerp.org` is an example. The documentation says:

```
If you have your DNS requests forwarded to your Application Server, put that in the host name section. If you leave this blank, you will have to access MixERP application using the Application Server IP Address or Network name.
```

So, if you leave this blank, you can access mixerp from

http://localhost

on the local machine.
