### ISSUE TITLE
getting ysod in the demo site

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#469]
when I click the goto pricing calculator button and after that i click the view demo button i get a ysod

![image](https://cloud.githubusercontent.com/assets/6284880/12996062/fa5132fa-d0f1-11e5-97d9-b003e2a9254c.png)

**Comment by gguruss** [comment]
the same problem persists if i click features and benefits

**Comment by mixerp** [comment]
Is this error persistent?

**Comment by gguruss** [comment]
the links i found faulty were

**Comment by gguruss** [comment]
Other faulty links:
https://design.mixerp.org/docs
