### ISSUE TITLE
Compiler Error on Lambda expression

### ISSUE THREAD

**Issue by manasheed** [mixerp/mixerp#471]
Hi,
I am new in Lambda expression. Using VS 2012 with DotNet framwork 4.5 (also tried on .net4) getting compiler errors on lambda expressions. Please someone guide how to resolve this.

1. Error in Lambda express on "=>":
File Name: MixERPCultureInfo.cs
Error on line 10:  Calendar => new GregorianCalendar(); saying ";" expected instead of "=>"

Similarly in almost all dal files e.g.
File Name: GetOfficeIdByLoginIdProcedure.cs
Line 22:  public override string _ObjectNamespace => "audit";

2. Error in PocoHelper.cs
on function return does not recognizes "?".
        public static string GetKeyProperty<T>(T poco)
        {
            string key = GetKeyName(poco);

            var a = poco.GetType()
                .GetProperties()
                .FirstOrDefault(p => p.GetCustomAttributes(typeof (ColumnAttribute), true)
                            .Any(ca => ((ColumnAttribute) ca).Name.Equals(key)));

            return a?.Name;
        }

Regards
Ashhar

**Comment by mixerp** [comment]
Use VS2015.
