### ISSUE TITLE
error while add new in Direct Purchase..

### ISSUE THREAD

**Issue by vbarve-iki** [mixerp/mixerp#472]
I am facing some errors while add new in direct purchase

can any one give the solution for it...!
![untitled](https://cloud.githubusercontent.com/assets/17696652/13635726/b79c7324-e623-11e5-94d7-595ed703d3bf.png)

**Comment by mixerp** [comment]
According to private messages received from you, it seems like you are using previous version of MixERP.

Follow this doc if you using MixERP without Visual Studio:

http://docs.mixerp.org/docs/deployment/iis.html

or follow this doc if you are using MixERP with Visual Studio

http://docs.mixerp.org/docs/developer/setting-up-your-development-environment.html

Also, if you are using Visual Studio, please make sure that you have properly setup and are familiar with using git, and read this as well

http://docs.mixerp.org/docs/developer/clone-mixerp.html
