### ISSUE TITLE
Cannot install sample PostgreSQL scripts

### ISSUE THREAD

**Issue by khoaho** [mixerp/mixerp#490]
Hi,

I follow the instruction (http://docs.mixerp.org/docs/developer/quickstart/part-1-installing-database.html) to create a new database in pqAdmin III, then open sample-db.sql to execute the script.

However, I keep getting errors. I created two schemas `core` and `office` per error requests. But I still get this error:

> ERROR:  relation "office.users" does not exist
CONTEXT:  SQL statement "CREATE TABLE core.attributes
        (
            attribute_id                            SERIAL NOT NULL PRIMARY KEY,
            attribute_code                          national character varying(12) NOT NULL UNIQUE,
            attribute_name                          national character varying(100) NOT NULL,
            audit_user_id                           integer NULL REFERENCES office.users(user_id),    
            audit_ts                                TIMESTAMP WITH TIME ZONE NULL 
                                                    DEFAULT(NOW())   
        )"
PL/pgSQL function inline_code_block line 11 at SQL statement
********** Error **********
ERROR: relation "office.users" does not exist
SQL state: 42P01
Context: SQL statement "CREATE TABLE core.attributes
        (
            attribute_id                            SERIAL NOT NULL PRIMARY KEY,
            attribute_code                          national character varying(12) NOT NULL UNIQUE,
            attribute_name                          national character varying(100) NOT NULL,
            audit_user_id                           integer NULL REFERENCES office.users(user_id),    
            audit_ts                                TIMESTAMP WITH TIME ZONE NULL 
                                                    DEFAULT(NOW())   
        )"
PL/pgSQL function inline_code_block line 11 at SQL statement

Thank you.

**Comment by khoaho** [comment]
I have it working by loading the sample SQL script at:
https://github.com/mixerp/mixerp/blob/master/src/FrontEnd/db/1.x/1.6/mixerp-incremental-sample.sql

This SQL script has everything for the demo website. However, after running the website up, it requires userId & password. I check the office.users table and see there are 3 available users (`sys`, `binod` and `demo`) with password text field which is encrypted.

I tried an empty password for `sys` with with "Select Your Branch" is "Mix Open Foundation" but could not get login. Could you please give me the password of user `sys` so I can have control of the website.

![image](https://cloud.githubusercontent.com/assets/1810890/17835209/60ae21c8-6726-11e6-94e5-033fc509e070.png)

Thank you.

**Comment by mixerp** [comment]
The admin user account is binod/binod. Sys user is not allowed to login.

**Comment by khoaho** [comment]
That userId/password works. Thank you. The app looks awesome!
