### ISSUE TITLE
missing icons in mixerp website

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#491]
![image](https://cloud.githubusercontent.com/assets/6284880/17823147/a37e8bfc-6620-11e6-8524-4a583d96d0e4.png)

mixerp website is missing icons

**Comment by mixerp** [comment]
Could you please hard refresh the browser? There does not seem to be an issue here. Thank you for pointing out.

**Comment by gguruss** [comment]
I hard refreshed the browser. I have tried it with all browsers still the same problem. I even tried it in different machines.

**Comment by gguruss** [comment]
![image](https://cloud.githubusercontent.com/assets/6284880/17902658/b1ce6816-692d-11e6-8034-acd1a3ba55d8.png)

This is the recent image of mixerp website that I get when i access it from a library computer.
