### ISSUE TITLE
employee and payrol component is not included in the source code.Kindly tell me about that component how to get it?

### ISSUE THREAD

**Issue by M-Bilal-ch** [mixerp/mixerp#493]
employee and payroll component is not added in the source code 
Kindly tell me about that component how to get it?

**Comment by binodnp** [comment]
You can find HRM source code in the MixERP repository:

https://github.com/mixerp/mixerp/tree/master/src/FrontEnd/Modules/HRM

**Comment by M-Bilal-ch** [comment]
hi
how to publish the code of mixerp? could you please help me in this regards
Thnakyou




*Regards,M.Bilal Ch*
*+92 312 2257510*

**Comment by M-Bilal-ch** [comment]
i try to published it but in publshed code it have .cs and .ascx files how
to exclude that ?



*Regards,M.Bilal Ch*
*+92 312 2257510*
