### ISSUE TITLE
Missing ScrudFactory Projects

### ISSUE THREAD

**Issue by dcji** [mixerp/mixerp#494]
Hey, 

I just downloaded the latest code. I assume that "No-Modules.sln" is the main solution for this application. However, I found some projects referenced incorrectly in this solution which I fixed by selecting them from correct location, but "**MixERP.Net.WebControls.ScrudFactory.Data.csproj**" and "**MixERP.Net.WebControls.ScrudFactory.csproj**" are not at all part of the the downloaded source code.

Need some help on this. 

![missing_projects](https://cloud.githubusercontent.com/assets/17051923/21545126/fc986428-cdfa-11e6-8e97-59b6be0d9d54.PNG)

**Comment by mixerp** [comment]
Please use `MixERP.Net.sln` instead.

**Comment by dcji** [comment]
Thanks!
