### ISSUE TITLE
.Net Core 2

### ISSUE THREAD

**Issue by myomyinthan** [mixerp/mixerp#497]
Hi ,
Any plan to upgrade .Net Core 2 Version? 
Thanks

**Comment by rbaz** [comment]
We can create one!

**Comment by albutta** [comment]
Is this project still alive and kicking, or has bitcoin killed it. 
I only get a thank you for your interest email from a no reply email.
I have a need for the latest version and want to convert the back-end to .net core 3

**Comment by rbaz** [comment]
I think yes its alive! 
try init project for your development environment.

**Comment by rbaz** [comment]
I create two database  postgreSql & sql Server. Now I will generate data context using EF Core!
Someone want to participate.
:)

**Comment by albutta** [comment]
I was thinking of dividing the system into micro services using EF Core.
