### ISSUE TITLE
transactions.get_accrued_interest(office_id integer, party_id bigint) returns null 

### ISSUE THREAD

**Issue by gguruss** [mixerp/mixerp#59]
please check the function in the following path
functions-and-logic-->logic--functions--transactions

transactions.get_accrued_interest(office_id integer, party_id bigint)
the function returns null

**Comment by gguruss** [comment]
transactions.get_closing_stock
function has a hard coded value of  0

**Comment by mixerp** [comment]
Since this was primarily a boilerplate function, we have a different implementation now. Instead of charging interest, we now charge late fee depending upon the payment terms. This function should be deleted.
