### ISSUE TITLE
Counter Setup is blank.

### ISSUE THREAD

**Issue by mixerp3** [mixerp/mixerp#60]
![user](https://cloud.githubusercontent.com/assets/10184034/6183140/e0108d7e-b305-11e4-9ba4-fc15b8be6b83.jpg)
![visual](https://cloud.githubusercontent.com/assets/10184034/6183144/e62f8a52-b305-11e4-884c-969df022f8ce.jpg)

**Comment by binodnp** [comment]
Solved.
