### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by mixerp4** [mixerp/mixerp#63]
![issue1](https://cloud.githubusercontent.com/assets/10184067/6210202/6b106038-b5f5-11e4-9b76-4e34c9817bd2.jpg)
When Is exemption is checked true and rate is greater than 0, this error displays on Sales Taxes

**Comment by binodnp** [comment]
Please check this error once again against the latest commit if it has already been solved.

**Comment by binodnp** [comment]
If this is still a valid issue, please feel free to re-open this.
