### ISSUE TITLE
 Error in one time setup

### ISSUE THREAD

**Issue by mixerp6** [mixerp/mixerp#65]
In the case of merge: If quantity is 1 million in both entry .it results 1,001,000.00.

**Comment by binodnp** [comment]
Solved.

**Comment by mixerp** [comment]
This bug has appeared once again. Need a thorough testing and fix for this.

**Comment by mixerp** [comment]
@mixerp6, do you have a qunit test to guarantee this will not occur again?

**Comment by mixerp6** [comment]
Qunit tests related to this issue were added on the commit 
https://github.com/mixerp/mixerp/commit/6c5c198b2186258c1337a8cdf4e31df69bc09d18

**Comment by mixerp** [comment]
Okay, fair enough.
