### ISSUE TITLE
End of Day Operation

### ISSUE THREAD

**Issue by nubiancc** [mixerp/mixerp#97]
when start end of day operation on brooklen branch get Error:
An exception of type 'MixERP.Net.Common.Base.MixERPException' occurred in MixERP.Net.Core.Modules.Finance.dll but was not handled in user code

Additional information: Access is denied. You are not authorized to post this transaction.

**Comment by mixerp** [comment]
nubiancc,

That behavior is expected. A user must have an elevated privilege to perform EOD operation. To elevate a user, please change the flag "elevated" to "Yes" on:

```Back Office-->Office Setup-->User Management-->Selected User-->Edit".

Please let me know if you have further questions.
